nes-games/config/routes.rb
Rails.application.routes.draw do
  resources :publishers
  resources :cartridges

end

nes-games/app/models/cartridge.rb
class Cartridge < ActiveRecord::Base
  belongs_to :publisher
end

nes-games/app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :cartridges
end

nes-games/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

nes-games/app/controllers/cartridges_controller.rb
class CartridgesController < ApplicationController
  before_action :set_cartridge, only: [:show, :edit, :update, :destroy]

  # GET /cartridges
  # GET /cartridges.json
  def index
    @cartridges = Cartridge.all
  end

  # GET /cartridges/1
  # GET /cartridges/1.json
  def show
  end

  # GET /cartridges/new
  def new
    @cartridge = Cartridge.new
  end

  # GET /cartridges/1/edit
  def edit
  end

  # POST /cartridges
  # POST /cartridges.json
  def create
    @cartridge = Cartridge.new(cartridge_params)

    respond_to do |format|
      if @cartridge.save
        format.html { redirect_to @cartridge, notice: 'Cartridge was successfully created.' }
        format.json { render :show, status: :created, location: @cartridge }
      else
        format.html { render :new }
        format.json { render json: @cartridge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cartridges/1
  # PATCH/PUT /cartridges/1.json
  def update
    respond_to do |format|
      if @cartridge.update(cartridge_params)
        format.html { redirect_to @cartridge, notice: 'Cartridge was successfully updated.' }
        format.json { render :show, status: :ok, location: @cartridge }
      else
        format.html { render :edit }
        format.json { render json: @cartridge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cartridges/1
  # DELETE /cartridges/1.json
  def destroy
    @cartridge.destroy
    respond_to do |format|
      format.html { redirect_to cartridges_url, notice: 'Cartridge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cartridge
      @cartridge = Cartridge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cartridge_params
      params.require(:cartridge).permit(:title, :colour, :publisher_id)
    end
end

nes-games/app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  before_action :set_publisher, only: [:show, :edit, :update, :destroy]

  # GET /publishers
  # GET /publishers.json
  def index
    @publishers = Publisher.all
  end

  # GET /publishers/1
  # GET /publishers/1.json
  def show
  end

  # GET /publishers/new
  def new
    @publisher = Publisher.new
  end

  # GET /publishers/1/edit
  def edit
  end

  # POST /publishers
  # POST /publishers.json
  def create
    @publisher = Publisher.new(publisher_params)

    respond_to do |format|
      if @publisher.save
        format.html { redirect_to @publisher, notice: 'Publisher was successfully created.' }
        format.json { render :show, status: :created, location: @publisher }
      else
        format.html { render :new }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publishers/1
  # PATCH/PUT /publishers/1.json
  def update
    respond_to do |format|
      if @publisher.update(publisher_params)
        format.html { redirect_to @publisher, notice: 'Publisher was successfully updated.' }
        format.json { render :show, status: :ok, location: @publisher }
      else
        format.html { render :edit }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publishers/1
  # DELETE /publishers/1.json
  def destroy
    @publisher.destroy
    respond_to do |format|
      format.html { redirect_to publishers_url, notice: 'Publisher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publisher
      @publisher = Publisher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publisher_params
      params.require(:publisher).permit(:name)
    end
end

nes-games/app/helpers/application_helper.rb
module ApplicationHelper
end

nes-games/app/helpers/cartridges_helper.rb
module CartridgesHelper
end

nes-games/app/helpers/publishers_helper.rb
module PublishersHelper
end

nes-games/app/views/cartridges/_form.html.erb
<%= form_for(@cartridge) do |f| %>
  <% if @cartridge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cartridge.errors.count, "error") %> prohibited this cartridge from being saved:</h2>

      <ul>
      <% @cartridge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :colour %><br>
    <%= f.text_field :colour %>
  </div>
  <div class="field">
    <%= f.label :publisher_id %><br>
    <%= f.collection_select(:publisher_id, Publisher.all, :id, :name, :include_blank => true ) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

nes-games/app/views/cartridges/edit.html.erb
<h1>Editing Cartridge</h1>

<%= render 'form' %>

<%= link_to 'Show', @cartridge %> |
<%= link_to 'Back', cartridges_path %>

nes-games/app/views/cartridges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cartridges</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cartridges.each do |cartridge| %>
      <tr>
        <td><%= cartridge.title %></td>
        <td><%= cartridge.colour %></td>
        <td><%= link_to 'Show', cartridge %></td>
        <td><%= link_to 'Edit', edit_cartridge_path(cartridge) %></td>
        <td><%= link_to 'Destroy', cartridge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cartridge', new_cartridge_path %>

nes-games/app/views/cartridges/new.html.erb
<h1>New Cartridge</h1>

<%= render 'form' %>

<%= link_to 'Back', cartridges_path %>

nes-games/app/views/cartridges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @cartridge.title %>
</p>
<p>
  <strong>Colour:</strong>
  <%= @cartridge.colour %>
</p>
<% if @cartridge.publisher %>
<p>
  <strong>Publisher:</strong>
  <%= @cartridge.publisher.name %>
</p>
<% end %>

<%= link_to 'Edit', edit_cartridge_path(@cartridge) %> |
<%= link_to 'Back', cartridges_path %>

nes-games/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NesGames</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

nes-games/app/views/publishers/_form.html.erb
<%= form_for(@publisher) do |f| %>
  <% if @publisher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publisher.errors.count, "error") %> prohibited this publisher from being saved:</h2>

      <ul>
      <% @publisher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

nes-games/app/views/publishers/edit.html.erb
<h1>Editing Publisher</h1>

<%= render 'form' %>

<%= link_to 'Show', @publisher %> |
<%= link_to 'Back', publishers_path %>

nes-games/app/views/publishers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Publishers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @publishers.each do |publisher| %>
      <tr>
        <td><%= publisher.name %></td>
        <td><%= publisher.cartridges.count %></td>
        <td><%= link_to 'Show', publisher %></td>
        <td><%= link_to 'Edit', edit_publisher_path(publisher) %></td>
        <td><%= link_to 'Destroy', publisher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Publisher', new_publisher_path %>

nes-games/app/views/publishers/new.html.erb
<h1>New Publisher</h1>

<%= render 'form' %>

<%= link_to 'Back', publishers_path %>

nes-games/app/views/publishers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @publisher.name %>
</p>
<p>
  <strong>Cartridges:</strong><br />
  <ul>
  <% @publisher.cartridges.each do |cartridge| %>
    <li><%= cartridge.title %></li>
  <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_publisher_path(@publisher) %> |
<%= link_to 'Back', publishers_path %>